#!/usr/bin/env bash
# a script to display information about subdomains of brvke.tech DNS


info_dig () {
    dig "${2}.${1}" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain '$2' is a " $4 " record and points to "$5}'
} 
	
if [ -z "$2" ]; then
    sub_domain=(www lb-01 web-01 web-02)
    for subdom in "${sub_domain[@]}"; do
        info_dig "$1" "$subdom"
    done
else
    info_dig "$1" "$2"
fi
exit 0

