#!/usr/bin/env bash
#custom header add
sudo apt-get -y update
sudo apt-get -y install nginx 
sudo ufw allow "Nignx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server;/a \\tlocation /redirect_me { \n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default
line='\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}'
echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "30i\ $line" /etc/nginx/sites-enabled/default
sudo sed -i "27 i\ \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
