#!/usr/bin/env bash
# configures a load balancer to to use a roundrobin algorithm

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy=2.7.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 492790-web-01 54.164.141.32:80 check\n\tserver 492790-web-02 34.229.189.54:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
