#!/usr/bin/env bash
# Bash Script to debug an ndinx server so that it is able to listen @80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
