#!/usr/bin/env bash
# This Script changes the etc/hosts file to wht is needed
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/'  ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo "8.8.8.8		facebook.com" >> /etc/hosts
